Proj/Areas/User/Controllers/ShoseController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Proj.Models;
using Proj.Areas.User.Services;
using OnlineSportShop.Areas.User.Services;
using Microsoft.AspNetCore.Identity;

namespace OnlineSportShop.Areas.User.Controllers
{
    [Area("User")]
    public class ShoseController : Controller
    {
        private readonly IProduct shose;
        private readonly ICartList CartList;
        private readonly UserManager<Proj.Models.User> userManager;
        private string loggedUser;
        public ShoseController(IProduct shose, ICartList CartList,
            UserManager<Proj.Models.User> userManager
            )
        {
            this.userManager = userManager;
            this.CartList = CartList;
            this.shose = shose;
        }

        //to git all product List
        public IActionResult Index(int ?id, string color, string gender)
        {
            ViewData["ColorFilter"] = color;
            ViewData["GenderFilter"] = gender;

            List<Product> shoseProductList = new List<Product>();
            
            if (color != null && gender == null)
            {
                shoseProductList = shose.GetShoes().Where(l => l.Color.ToLower() == color.ToLower()).ToList();
            }
            else if(gender != null && color == null)
            {
                shoseProductList = shose.GetShoes().Where(l => l.Gender.ToString().ToLower() == gender.ToLower()).ToList();
            }else if (color!=null && gender!=null) {
                shoseProductList = shose.GetShoes().Where(
                    l => (l.Gender.ToString().ToLower() == gender.ToLower()) && (l.Color.ToLower() == color.ToLower()) ).ToList();
            }
            else
            {
                shoseProductList = shose.GetShoes();
            }
            ViewBag.shoseProductList = shoseProductList;
            
            return View();
        }
        public IActionResult getShoseProduct(int id)
        {
            Product _shose = shose.GetProduct(id,ProductType.Shoes);
            ViewBag._shose = _shose;
            return View();
        }
        public IActionResult AddToCart(int id)
        {
            loggedUser = this.userManager.GetUserId(HttpContext.User);
            if (loggedUser != null)
            {
                var productItem = shose.GetProduct(id, ProductType.Shoes);
                CartList.AddToCart(productItem, loggedUser);
                return RedirectToAction("Index");
            }
            else
            {

                return Redirect("https://localhost:44363/Identity/Account/Login");

            }
        }
    }
}

Proj/Areas/User/Views/Shose/Index.cshtml
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    List<Proj.Models.Product> shoses = ViewBag.shoseProductList;


}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="~/css/productCard.css" rel="stylesheet" />

<div style="text-align:center" class="alert-dark"><a asp-action="Index"><h1>Shoes</h1></a></div>

<div class="container d-flex justify-content-center mt-50 mb-50">
    @using (Html.BeginForm("index", "Shose", FormMethod.Post))
    {
        <div class="form-actions no-color d-inline-block">
            <p>
                <i class="fas fa-search"></i>
                find by color <input class="bi bi-search form-control" type="text" name="color" value="@ViewData["ColorFilter"]" placeholder="Seach.." />
            </p>
        </div>
        <div class="form-actions no-color d-inline-block">
            <p>
                <i class="fas fa-search"></i>
                find by gender<input class="form-control" type="text" name="gender" value="@ViewData["GenderFilter"]" placeholder="Seach.." />
            </p>
        </div>
        <div style="text-align:center">
            <input type="submit" value="search" class="btn btn-primary" />
        </div>
    }
</div>




@if (shoses.Count() < 4 && shoses.Count() != 0)
{
    <div class="container d-flex justify-content-center mt-50 mb-50">
        <div class="row">
            @foreach (var shose in shoses)
            {
                var srcImg = "~/images/Shoes/" + @shose.Source;

                <div class="col-6 mt-2">
                    <div class="card">
                        <div class="card-body">

                            <a asp-area="User" asp-controller="Shose" asp-action="getShoseProduct" asp-route-id="@shose.ID">
                                <div class="card-img-actions">
                                    <img asp-append-version="true" src=@srcImg class="card-img img-fluid" width="96" height="250" alt="" />
                                </div>
                            </a>
                        </div>
                        <div class="card-body bg-light text-center">
                            <div class="mb-2">
                                <h6 class="font-weight-semibold mb-2">
                                    <a href="#" class="text-default mb-2" data-abc="true">
                                        @shose.Name
                                    </a>
                                </h6>
                                <a href="#" class="text-muted" data-abc="true">@shose.Brand</a>
                            </div>
                            <h3 class="mb-0 font-weight-semibold">$@shose.Price</h3>
                            <div> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> </div>
                            <div class="text-muted mb-3">34 reviews</div>
                            <a asp-action="AddToCart" asp-route-id="@shose.ID" class="btn bg-cart">Add to cart</a>
                        </div>
                    </div>
                </div>


            }

        </div>



    </div>
}
else if (shoses.Count() == 0)
{
    <a asp-area="" asp-controller="Home" asp-action="Index">
        <center>
            <img class="img-fluid" src="~/images/no-products-found.png" />
        </center>
    </a>


}
else
{
    <div class="container d-flex justify-content-center mt-50 mb-50">
        <div class="row">
            @foreach (var shose in shoses)
            {
                var srcImg = "~/images/Shoes/" + @shose.Source;

                <div class="col-4 mt-2">
                    <div class="card">
                        <div class="card-body">

                            <a asp-area="User" asp-controller="Shose" asp-action="getShoseProduct" asp-route-id="@shose.ID">
                                <div class="card-img-actions">
                                    <img asp-append-version="true" src=@srcImg class="card-img img-fluid" width="96" height="250" alt="" />
                                </div>
                            </a>
                        </div>
                        <div class="card-body bg-light text-center">
                            <div class="mb-2">
                                <h6 class="font-weight-semibold mb-2">
                                    <a href="#" class="text-default mb-2" data-abc="true">
                                        @shose.Name
                                    </a>
                                </h6>
                                <a href="#" class="text-muted" data-abc="true">@shose.Brand</a>
                            </div>
                            <h3 class="mb-0 font-weight-semibold">$@shose.Price</h3>
                            <div> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> </div>
                            <div class="text-muted mb-3">34 reviews</div>
                            <a asp-action="AddToCart" asp-route-id="@shose.ID" class="btn bg-cart">Add to cart</a>
                        </div>
                    </div>
                </div>


            }

        </div>



    </div>
}

Proj/Areas/User/Views/Shose/getShoseProduct.cshtml
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "getShoseProduct";
    var shose = ViewBag._shose;
    var srcImg = "~/images/Shoes/" + @shose.Source;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="~/css/ClothesDetails.css" rel="stylesheet" />

<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img asp-append-version="true" id="main-image" src=@srcImg width="250" /> </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                <i class="fa fa-long-arrow-left"></i> 
                                <a asp-action="Index" class="ml-1">Back</a> 
                                    </div> <i class="fa fa-shopping-cart text-muted"></i>
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@shose.Name/@shose.Brand</span>
                              
                                <span>@shose.Color /</span>

                                <span>@shose.Gender</span>
                                <div class="price d-flex flex-row align-items-center">
                                    <span class="act-price">$@shose.Price</span>
                                </div>
                            </div>
                            <p class="about">@shose.Discrbtion</p>
                            <div class="sizes mt-5">
                                <h6 class="text-uppercase">Size</h6>
                                <label >Available Size : </label>
                                
                                <label class="radio"> 
                                <input type="radio" name="size" value="39"> 
                                <span>39</span> </label> <label class="radio">
                                <input type="radio" name="size" value="40"> 
                                <span>40</span> </label> <label class="radio">
                                <input type="radio" name="size" value="42"> <span>42</span> </label> 
                                <label class="radio"> <input type="radio" name="size" value="44"> <span>44</span> </label>
                            </div>
                            <div class="cart mt-4 align-items-center">
                                <a  asp-action="AddToCart" asp-route-id="@shose.ID"  class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</a>
                                <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>