Proj/Areas/User/Controllers/MachineController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineSportShop.Areas.User.Services;
using Proj.Areas.User.Services;
using Proj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineSportShop.Areas.User.Controllers
{     [Area("User")]
        
    public class MachineController : Controller
    {
        private readonly IProduct service;
        private readonly ICartList CartList;
        private readonly UserManager<Proj.Models.User> userManager;
        private string loggedUser;
        public MachineController(IProduct service, ICartList CartList,
            UserManager<Proj.Models.User> userManager
            )
        {
            this.userManager = userManager;
            this.CartList = CartList;
            this.service = service;
        }

        public IActionResult Index(int? id, string color, string name)
        {
            ViewData["ColorFilter"] = color;
            ViewData["NameFilter"] = name;

            List<Product> machineProductList = new List<Product>();

            if (color != null && name == null)
            {
                machineProductList = service.GetMachines().Where(l => l.Color.ToLower() == color.ToLower()).ToList();
            }
            else if (name != null && color == null)
            {
                machineProductList = service.GetMachines().Where(l => l.Name.ToString().ToLower() == name.ToLower()).ToList();
            }
            else if (color != null && name != null)
            {
                machineProductList = service.GetMachines().Where(
                    l => (l.Name.ToString().ToLower() == name.ToLower()) && (l.Color.ToLower() == color.ToLower())).ToList();
            }
            else
            {
                machineProductList = service.GetMachines();
            }
            ViewBag.machineProductList = machineProductList;

            return View();
        }

        //// GET: Admin/Clothes/Details/5
        public IActionResult Details(int id)
        {

            Product machine = service.GetProduct(id,ProductType.Machines);
            ViewBag.machine = machine;
            return View();

        }
        public IActionResult AddToCart(int id)
        {
            loggedUser = this.userManager.GetUserId(HttpContext.User);
            if (loggedUser != null)
            {
                var productItem = service.GetProduct(id, ProductType.Machines);
                CartList.AddToCart(productItem, loggedUser);
                return RedirectToAction("Index");
            }
            else
            {

                return Redirect("https://localhost:44363/Identity/Account/Login");

            }
        }

    }
}

Proj/Areas/User/Views/Machine/Details.cshtml
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "Details";
    var machine = ViewBag.machine;
    var srcImg = "~/images/Machines/" + machine.Source;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="~/css/ClothesDetails.css" rel="stylesheet" />

<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img asp-append-version="true" id="main-image" src=@srcImg width="250" /> </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                    <i class="fa fa-long-arrow-left"></i>
                                    <a asp-action="Index" class="ml-1">Back</a>
                                </div> <i class="fa fa-shopping-cart text-muted"></i>
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@machine.Name</span>

                                <span>@machine.Color /</span>

                                <div class="price d-flex flex-row align-items-center">
                                    <span class="act-price">$@machine.Price</span>
                                   
                                </div>
                            </div>
                            <p class="about">@machine.Discrbtion</p>
                          
                            <div class="cart mt-4 align-items-center">
                                <a asp-action="AddToCart" asp-route-id="@machine.ID"  class="btn btn-danger text-uppercase mr-2 px-4">Add to cart</a>
                                <i class="fa fa-heart text-muted"></i> <i class="fa fa-share-alt text-muted"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Proj/Areas/User/Views/Machine/Index.cshtml
@model IEnumerable<Proj.Models.Product>
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@addTagHelper "*,Microsoft.AspNetCore.Mvc.Rendering"
@{
    List<Proj.Models.Product> machines = ViewBag.machineProductList;


}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="~/css/productCard.css" rel="stylesheet" />

<div style="text-align:center" class="alert-dark"><a asp-action="Index"><h1>Machines</h1></a></div>

<div class="container d-flex justify-content-center mt-50 mb-50">
    @using (Html.BeginForm("index", "Machine", FormMethod.Post))
    {
        <div class="form-actions no-color d-inline-block">
            <p>
                <i class="fas fa-search"></i>
                find by color <input class="bi bi-search form-control" type="text" name="color" value="@ViewData["ColorFilter"]" placeholder="Seach.." />
            </p>
        </div>
        <div class="form-actions no-color d-inline-block">
            <p>
                <i class="fas fa-search"></i>
                find by name<input class="form-control" type="text" name="name" value="@ViewData["NameFilter"]" placeholder="Seach.." />
            </p>
        </div>
        <div style="text-align:center">
            <input type="submit" value="search" class="btn btn-primary" />
        </div>
    }
</div>


@if (machines.Count() < 4 && machines.Count() != 0)
{
    <div class="container d-flex justify-content-center mt-50 mb-50">
        <div class="row">
            @foreach (var machine in machines)
            {
                var srcImg = "~/images/Machines/" + machine.Source;

                <div class="col-6 mt-2">
                    <div class="card">
                        <div class="card-body">
                            <a asp-area="User" asp-controller="Machine" asp-action="Details" asp-route-id="@machine.ID">
                                <div class="card-img-actions">
                                    <img asp-append-version="true" src=@srcImg class="card-img img-fluid" width="96" height="250" alt="" />
                                </div>
                            </a>
                        </div>
                        <div class="card-body bg-light text-center">
                            <div class="mb-2">
                                <h6 class="font-weight-semibold mb-2">
                                    <a href="#" class="text-default mb-2" data-abc="true">
                                        @machine.Discrbtion
                                    </a>
                                </h6>
                                <a href="#" class="text-muted" data-abc="true">@machine.Name</a>
                            </div>
                            <h3 class="mb-0 font-weight-semibold">$@machine.Price</h3>
                            <div> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> </div>
                            <div class="text-muted mb-3">34 reviews</div> 
                            <a class="btn bg-cart" asp-action="AddToCart" asp-route-id="@machine.ID" ><i class="fa fa-cart-plus mr-2"></i> Add to cart</a>
                        </div>
                    </div>
                </div>


            }

        </div>



    </div>
}
else if (machines.Count() == 0)
{

    <a asp-area="" asp-controller="Home" asp-action="Index">
        <center>
            <img class="img-fluid" src="~/images/no-products-found.png" />
        </center>
    </a>
}
else
{
    <div class="container d-flex justify-content-center mt-50 mb-50">
        <div class="row">
            @foreach (var machine in machines)
            {
                var srcImg = "~/images/Machines/" + machine.Source;

                <div class="col-4 mt-2">
                    <div class="card">
                        <div class="card-body">


                            <a asp-area="User" asp-controller="Machine" asp-action="Details" asp-route-id="@machine.ID">
                                <div class="card-img-actions">
                                    <img asp-append-version="true" src=@srcImg class="card-img img-fluid" width="96" height="250" alt="" />
                                </div>
                            </a>
                        </div>
                        <div class="card-body bg-light text-center">
                            <div class="mb-2">

                                <a href="#" class="text-muted" data-abc="true">@machine.Name</a>
                            </div>
                            <h3 class="mb-0 font-weight-semibold">$@machine.Price</h3>
                            <div> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> <i class="fa fa-star star"></i> </div>
                            <div class="text-muted mb-3">34 reviews</div>
                            <a class="btn bg-cart" asp-action="AddToCart" asp-route-id="@machine.ID" ><i class="fa fa-cart-plus mr-2"></i> Add to cart</a>
                        </div>
                    </div>
                </div>


            }

        </div>



    </div>
}